name: Terraform Azure Windows Pipeline

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Terraform folder path"
        required: true
        default: "rg"

permissions:
  id-token: write
  contents: read

jobs:
  
  terraform_plan:
    name: "Terraform Plan"
    runs-on: [self-hosted, Windows]
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.working_directory }}

      - name: Terraform Plan
        run: terraform plan -out="${{ github.workspace }}\tfplan"
        working-directory: ${{ github.event.inputs.working_directory }}

      - name: Upload Plan File
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-artifact
          path: ${{ github.workspace }}\tfplan

 
  manual_approval:
    name: "Waiting for Approval"
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: dev 
    steps:
      - name: Approved
        run: echo "Plan approved by user. Starting Apply..."

 
  terraform_apply:
    name: "Terraform Apply"
    needs: manual_approval
    runs-on: [self-hosted, Windows]
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with:
          name: tf-plan-artifact
          path: ${{ github.workspace }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.working_directory }}

      - name: Terraform Apply
        run: terraform apply -auto-approve "${{ github.workspace }}\tfplan"
        working-directory: ${{ github.event.inputs.working_directory }}
