on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Path to Terraform working directory"
        required: true
        default: "./rg"
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: Terraform on Window Self-Host Runner
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      WORK_DIR: ${{ github.event.inputs.working_directory }}
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5.0.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Aap apni pasand ka version likh sakte hain
   
       #Terraform Init
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
      # Terraform Validate
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORK_DIR }}
      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORK_DIR }}

  manual_validation:
    name: Manual Validation (Environment Approval)
    needs: terraform
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Awaiting Approval
        run: echo "Waiting for environment approval to proceed to apply..."

  apply:
    name: Terraform Apply (Approved)
    needs: manual_validation
    runs-on:  ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      WORK_DIR: ${{ github.event.inputs.working_directory }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Aap apni pasand ka version likh sakte hai
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        
      - name: Terraform Apply
        id: apply
        working-directory: ${{ github.workspace }}${{ '/' }}${{ github.event.inputs.working_directory }}
        run: terraform apply -auto-approve
