name: Terraform Windows Workflow

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Path to Terraform working directory"
        required: true
        default: "rg"

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: windows-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false # Ye sabse important fix hai

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.event.inputs.working_directory }}

      - name: Terraform Plan
        id: plan
        # Windows pe path ke liye slash direction change ki hai
        run: terraform plan -out="${{ github.workspace }}\tfplan"
        working-directory: ${{ github.event.inputs.working_directory }}

      - name: Upload Plan Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-file
          path: ${{ github.workspace }}\tfplan
